### ISSUE TITLE
Change above to below

### ISSUE THREAD

**Issue by AlexanderYastrebov** [DennisYurichev/RE-for-beginners#479]
https://github.com/DennisYurichev/RE-for-beginners/blob/master/patterns/03_printf/x86/x86_EN.tex#L157

```
Everything above the stack pointer (\ac{SP}) 
is \IT{noise} or \IT{\garbage{}} and has no meaning at all.
```

`above` probably should be changed to `below` since stack grows downwards.
Additional clarification could be made about everything **above** stack pointer - those are stack frames of call chain.

**Comment by DennisYurichev** [comment]
Let me think... it's "above" visually, if you enumerate stack entries...

**Comment by AlexanderYastrebov** [comment]
Ok, agree, above/below depends on perspective
