### ISSUE TITLE
Explanation of stmia in ARM

### ISSUE THREAD

**Issue by neverxie** [DennisYurichev/RE-for-beginners#535]
https://github.com/DennisYurichev/RE-for-beginners/blob/226aadf82e4c0cb5cc1a10249554f9dca447793a/patterns/03_printf/ARM/ARM8_EN.tex#L64
hello, I have doubts about this sentence in the book.
`stmia`
i: increase, a: after operation.
it means that save the data to memory first, then add pointers.
‘!’ is to change the R12 register.
`.text:00000044 0F 00 8C E8 STMIA R12, {R0-R3}`
no '!' in this code, so R12 is not to be increased by 4 after each register value is written.
`stmia r12!, {r0-r3}`R12 is to be increased by 4 after each register value is written.

**Comment by DennisYurichev** [comment]
See here.. https://github.com/DennisYurichev/RE-for-beginners/blob/master/patterns/ARM/post_pre_index_EN.tex

**Comment by DennisYurichev** [comment]
But thanks for your attention...

**Comment by DennisYurichev** [comment]
I'm open for suggestions and ideas...

**Comment by neverxie** [comment]
@liangyongxiang
