### ISSUE TITLE
Russian translation line length

### ISSUE THREAD

**Issue by BondarenkoArtur** [DennisYurichev/RE-for-beginners#594]
Today I found that some of lines in russian PDF are longer than expected.
Here is second page (23/1049) of book. One word is cropped at all...
![image](https://user-images.githubusercontent.com/9720950/64690878-227a4000-d49a-11e9-8213-9d819840bdd8.png)

**Comment by BondarenkoArtur** [comment]
Here is PDF that I was using
https://beginners.re/RE4B-RU.pdf

**Comment by DennisYurichev** [comment]
https://github.com/DennisYurichev/RE-for-beginners/commit/9321727a487f6b7b8dbb35cdd2b4264bab6eb91e
